version: '2'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=docker_playground.dev
    volumes:
      - .:/docker_playground
    ports:
      - "8000:8000"
    depends_on: 
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=docker_playground
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=docker_playground
    volumes:
      - ./docker/postgresql:/var/lib/postgresql
    expose:
     - "5432"
