version: '2'
services:
  web:
    build: .
    command: uwsgi docker_playground.ini
    volumes:
      - .:/docker_playground
  nginx:
    build: deploy/dev/nginx/
    volumes:
      - .:/docker_playground
    ports:
      - "80:80"
    depends_on: 
      - web
